version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/weather-app
    overwrite: yes
permissions:
  - object: /home/ec2-user/weather-app/scripts
    pattern: "**"
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/configure_systemd.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root

